openapi: 3.0.4
info:
  title: Number to Words
  description: Number to Words is a simple tool for converting numbers to words. It returns the number in words.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/numbertowords:
    get:
      summary: Convert Number
      description: Number to Words is a simple tool for converting numbers to words. It returns the number in words.
      operationId: numbertowords
      parameters:
      - name: number
        in: query
        schema:
          type: number
        required: true
        description: The number to convert to words
        example: '975.07'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  number: 975.07
                  words: nine hundred seventy-five point zero seven
                  ordinal: nine hundred seventy-fifth point zero seven
                  numberOfDigits_numeric: 3
                  numberOfDigits_words: three
                  eachNumber:
                  - nine
                  - seven
                  - five
                  afterDecimal:
                    number: '07'
                    words:
                    - zero
                    - seven
                    numberOfDigits_numeric: 2
                    numberOfDigits_words: two
                  locale: en-US
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
